### ISSUE TITLE
Running npm start gives elasticsearch connection refused error.

### ISSUE THREAD

**Issue by pallaviraman** [DilipKunderu/SEfa17#15]
![capture](https://user-images.githubusercontent.com/22402851/31641451-bd4acfe8-b2b2-11e7-8963-16914aa35c65.PNG)

**Comment by chakrabortysaptarshi** [comment]
Open http://localhost:9200/ from your browser and it should show something like this, if elasticsearch is running -

`{
  "name" : "DESKTOP-303DLR3",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "a8uFrF-rQUmYTOALmbKu4w",
  "version" : {
    "number" : "5.6.0",
    "build_hash" : "781a835",
    "build_date" : "2017-09-07T03:09:58.087Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.0"
  },
  "tagline" : "You Know, for Search"
`}``

Otherwise, please check your installation.

**Comment by pallaviraman** [comment]
Installation was good but forgot to run bin\elasticsearch.bat to start the server and keep it running. We should mention this in README.

**Comment by chakrabortysaptarshi** [comment]
Closing this now as it got resolved.
